# https://game.ci/docs/github/builder
name: Build and publish to Itch

on:
  push:
    branch:
      - main
jobs:
  build:
    name: Build my project
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true

      # Cache
      - uses: actions/cache@v2
        with:
          path: Library
          key: Library

      # Test
      # - name: Run tests
      #   uses: game-ci/unity-test-runner@v2
      #   env:
      #     UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
      #   with:
      #     githubToken: ${{ secrets.GITHUB_TOKEN }}

      # Build
      - name: Build project
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        # https://game.ci/docs/github/builder#configuration-options
        with: 
          targetPlatform: WebGL

      # Output
      - uses: actions/upload-artifact@v2
        id: unity-build
        with:
          name: this_build # TODO use versioning?
          path: build/WebGL/WebGL
  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build
        uses: actions/download-artifact@v2
        with:
          name: this_build
          path: this_build
      - name: Zip build
        uses: thedoctor0/zip-release@master
        with:
          path: ./this_build
          filename: 'this_build.zip'
      - name: deploy to itch.io (HTML5)
        uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: html
          ITCH_GAME: ci-test
          ITCH_USER: goondrious
          PACKAGE: this_build.zip
          # VERSION: ${{ steps.unity_build.outputs.version }}
